services:
  app:
    build: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./frontend:/app/frontend
      - ./backend:/app
    restart: unless-stopped
